import {readFile,writeFile} from 'node:fs/promises';
const original=await readFile(new URL('../index.html',import.meta.url),'utf8');
let sidebar=original.match(/<aside class="sidebar">[\s\S]*?<\/aside>/)[0];
const labels={projects:['项目','xiang','mu'],knowledge:['知识','zhi','shi'],sources:['资料','zi','liao']};
for(const [key,[label,a,b]] of Object.entries(labels)){sidebar=sidebar.replace(`data-view="${key}"><span>${key==='projects'?'◇':key==='knowledge'?'✦':'▤'}</span>${label}`,`data-view="${key}" aria-label="${label}"><span>${key==='projects'?'◇':key==='knowledge'?'✦':'▤'}</span><svg class="nav-lettering" viewBox="0 0 210 100" aria-hidden="true"><use href="nav-lettering.svg#${a}" width="100" height="100"/><use href="nav-lettering.svg#${b}" x="110" width="100" height="100"/></svg><span class="nav-copy">${label}</span>`);}
sidebar=sidebar.replace('nav-item active','nav-item').replace('nav-item sub" data-view="projects"','nav-item sub active" data-view="projects"').replace('<div id="areaNavList" class="area-nav-list"></div>','<div id="areaNavList" class="area-nav-list"><button data-area="AI 工具与自动化">AI 工具与自动化</button><button data-area="创意与设计">创意与设计</button></div>');
const topbar=original.match(/<header class="topbar">[\s\S]*?<\/header>/)[0];
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>知行台 · 局部设计微调</title><link rel="stylesheet" href="../assets/fonts/fonts.css"><link rel="stylesheet" href="../styles.css"><link rel="stylesheet" href="refined.css"><script src="refined.js" defer></script></head><body data-refinement="on" data-lettering="on"><div class="app-shell">${sidebar}<main>${topbar}<section class="view active"><div class="collection-toolbar"><div class="collection-filters"><div class="filter-row" id="filterRow"></div><label class="collection-area-filter"><span>按领域查看</span><select id="domain"><option value="all">全部领域</option><option>AI 工具与自动化</option><option>创意与设计</option></select></label></div><div class="collection-actions"><div class="display-toggle" role="group" aria-label="内容呈现方式"><button data-display="gallery">画廊</button><button data-display="list" class="active">列表</button></div><button class="primary-small" id="newCard">＋ 新建项目</button></div></div><div class="stats-row" id="stats"></div><div class="collection-list" id="collectionList"></div></section></main></div><div class="refine-controls" aria-label="设计对比"><span class="control-dot"></span><span>局部微调提案</span><div class="mode"><button data-mode="off" aria-pressed="false">原版</button><button data-mode="on" aria-pressed="true">微调</button></div><label><input id="lettering" type="checkbox" checked>SVG 字形</label></div><dialog class="refined-dialog" id="preview"><header><span class="entry-type" id="previewType"></span><button id="closePreview" aria-label="关闭">×</button></header><h2 id="previewTitle"></h2><span class="type-chip--area" style="display:inline-block;padding:4px 12px;border:1px solid;border-radius:999px;font-size:11px" id="previewArea"></span><div class="preview-canvas"><div class="preview-note"><strong>原始内容</strong><p id="previewBody"></p></div></div><footer>视觉演示 · 正式工作台的数据不受影响</footer></dialog><div class="demo-toast" id="toast" hidden></div></body></html>`;
await writeFile(new URL('refined.html',import.meta.url),html);

