const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=[
['projects','视频黑边检测工具','现成能力\nFFmpeg：负责读取和分析各种视频；cropdetect：提供现成的黑边候选区域检测。\n需要自己判断\n我负责确定抽样位置、异常标准、误判处理和验收。','进行中','AI 工具与自动化'],
['projects','钉钉跨表统计工具','现成能力\n钉钉 MCP：连接钉钉调用表格能力。\n需要自己判断\n我负责确认字段含义、清洗标准、人员映射和统计口径。','进行中','AI 工具与自动化'],
['knowledge','通用核心与业务外壳应该分开','已有库和工具负责通用能力，自己的精力用于只有业务现场才知道的规则。\n\n适用场景\n开发内部工具、选择开源项目、使用 MCP。','已确认','AI 工具与自动化'],
['knowledge','好的工具应降低切换成本','把常用的信息和操作放在同一个空间，让工具顺着思考的节奏工作。','待验证','创意与设计'],
['sources','Tyrrrz / YoutubeDownloader','同事推荐的现成下载工具，后续与自己的 yt-dlp GUI 对照研究。','未读','AI 工具与自动化'],
['sources','UI 设计灵感集','少量高纯度色块、几何化字形与清晰的信息层级。','已读','创意与设计']
];
const names={projects:'项目',knowledge:'知识',sources:'资料',home:'工作台',inbox:'随手记',areas:'领域',graph:'关系图谱',trash:'回收站'};
let view='projects',display='list',status='全部',timer;
function toast(t){$('#toast').hidden=false;$('#toast').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,2500);}
function base(){return data.filter(i=>['home','areas','graph'].includes(view)||i[0]===view);}
function render(){const rows=base(),statuses=['全部',...new Set(rows.map(i=>i[3]))];if(!statuses.includes(status))status='全部';$('#viewTitle').textContent=names[view];$('#viewEyebrow').textContent='2026 · 个人知识系统';$('#newCard').textContent='＋ 新建'+(['projects','knowledge','sources'].includes(view)?names[view]:'卡片');
document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-display]').forEach(b=>{b.classList.toggle('active',b.dataset.display===display);b.setAttribute('aria-pressed',String(b.dataset.display===display));});$('#filterRow').innerHTML=statuses.map(s=>`<button class="filter-button ${status===s?'active':''}" data-status="${s}" aria-pressed="${status===s}">${s}</button>`).join('');
const query=$('#searchInput').value.trim().toLowerCase(),domain=$('#domain').value,visible=rows.filter(i=>(status==='全部'||i[3]===status)&&(domain==='all'||i[4]===domain)&&(i[1]+i[2]).toLowerCase().includes(query));$('#stats').innerHTML=`<div class="stat"><b>${visible.length}</b><span>${names[view]}总数</span></div>`;$('#collectionList').classList.toggle('content-gallery',display==='gallery');
$('#collectionList').innerHTML=visible.map(i=>{const type=i[0]==='projects'?'project':i[0]==='knowledge'?'knowledge':'source',pill=`<span class="status-pill status--${i[3]==='进行中'?'doing':i[3]==='已确认'||i[3]==='已读'?'done':'todo'}">${i[3]}</span>`;return `<article class="entry-card"><button class="entry-open" data-open="${data.indexOf(i)}">${display==='gallery'?`<span class="entry-gallery-heading"><span class="entry-type entry-type--${type}">${names[i[0]]}</span>${pill}</span><h3>${esc(i[1])}</h3><p>${esc(i[2])}</p><span class="entry-meta">2026-10-01</span>`:`<span class="entry-type entry-type--${type}">${names[i[0]]}</span><div><h3>${esc(i[1])}</h3></div><span class="entry-meta">${pill}<br>2026-10-01</span>`}</button><div class="card-relations"><div class="relation-group"><span class="relation-kind">所属领域 · 分类标签</span><div><button class="type-chip--area" data-area="${i[4]}"><small>领域</small>${i[4]}</button></div></div><div class="relation-group"><span class="relation-kind">关联内容</span><div><button class="type-chip--knowledge" data-open="2"><small>知识</small>通用核心与业务外壳应该分开</button></div></div></div></article>`;}).join('')||'<div class="empty-state"><b>暂无匹配内容</b><span>试试其他关键词或筛选条件。</span></div>';}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;status='全部';$('#searchInput').value='';$('#domain').value='all';render();}if(b.dataset.display){display=b.dataset.display;render();}if(b.dataset.status){status=b.dataset.status;render();}if(b.dataset.mode){document.body.dataset.refinement=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));if(b.dataset.mode==='off'){$('#lettering').checked=false;document.body.dataset.lettering='off';}else{$('#lettering').checked=true;document.body.dataset.lettering='on';}}if(b.dataset.area){$('#domain').value=b.dataset.area;render();}if(b.dataset.open!==undefined){const i=data[+b.dataset.open];$('#previewTitle').textContent=i[1];$('#previewBody').textContent=i[2];$('#previewType').textContent=names[i[0]];$('#previewArea').textContent=i[4];if(!$('#preview').open)$('#preview').showModal();}if(['quickCapture','openAssetImport','newCard','openDataManager','resetDemo'].includes(b.id))toast('这是局部视觉提案，正式工作台的数据不受影响。');});
$('#lettering').onchange=e=>document.body.dataset.lettering=e.target.checked?'on':'off';$('#searchInput').oninput=render;$('#domain').onchange=render;$('#closePreview').onclick=()=>$('#preview').close();document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus();}});render();

