/* Appearance profiles are local preferences; uploaded backgrounds stay as Blobs. */
(()=>{
  const settingsKey='knowledge-workbench-appearance',modeKey='knowledge-workbench-theme';
  const isSettingsWindow=document.body.classList.contains('appearance-window');
  const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('workbench-appearance'):null;
  let settingsWindow;
  const light={baseTheme:'light',baseColor:'#ffffff',cardColor:'#fafbfd',cardColorCustom:false,rightAngle:0,leftAngle:0,rightWidth:1440,rightHeight:960,leftWidth:1240,leftHeight:880,glowEnabled:true,rightColor:'#9dddd2',rightOpacity:0,leftColor:'#aed2eb',leftOpacity:8,listRadius:14,galleryRadius:17.5,tagRadius:9,fillColor:'#ffffff',fill:21,blur:11.5,saturation:77,outline:38,highlight:41.5,shadedEdge:26,angle:175.5,shadowOpacity:10,shadowSize:11,shadowOffset:6,imageOpacity:100,imageFit:'cover'};
  const dark={...light,baseTheme:'dark',baseColor:'#101116',cardColor:'#1b1d25',rightWidth:1800,rightHeight:900,leftWidth:1200,leftHeight:900,glowEnabled:true,rightColor:'#586384',rightOpacity:22,leftColor:'#334157',leftOpacity:15,fillColor:'#7d7d7d',fill:13.5,blur:10,saturation:90,outline:0,highlight:81,shadedEdge:17,angle:155,shadowOpacity:29,shadowSize:8};
  Object.assign(light,{plateEnabled:false,plateColor:'#ffffff',plateOpacity:24,plateBlur:18,plateSaturation:120,plateBrightness:100,plateHighlight:25});
  Object.assign(dark,{plateEnabled:false,plateColor:'#242630',plateOpacity:30,plateBlur:18,plateSaturation:120,plateBrightness:100,plateHighlight:12});
  const defaults={light,dark,custom:{...light}};
  let settings={light:{...light},dark:{...dark},custom:{...light}},mode='light',imageUrl=null,imageName='',dialog,uploading=false;
  const colorDefs=[['baseColor','背景底色'],['cardColor','卡片窗口底色'],['rightColor','右侧渐变颜色'],['leftColor','左侧渐变颜色'],['fillColor','玻璃底色（列表／画廊）']];
  const numericDefs=[['rightAngle','右侧渐变角度',0,360,'°'],['leftAngle','左侧渐变角度',0,360,'°'],['rightWidth','右侧渐变宽度',100,3000,'px'],['rightHeight','右侧渐变高度',100,2000,'px'],['leftWidth','左侧渐变宽度',100,3000,'px'],['leftHeight','左侧渐变高度',100,2000,'px'],['rightOpacity','右侧渐变强度',0,100,'%'],['leftOpacity','左侧渐变强度',0,100,'%'],['imageOpacity','背景图片强度',0,100,'%'],['listRadius','列表圆角',0,40,'px'],['galleryRadius','画廊圆角',0,40,'px'],['tagRadius','标签圆角',0,15,'px'],['fill','玻璃填充',0,100,'%'],['blur','背景模糊',0,30,'px'],['saturation','背景饱和度',0,200,'%'],['outline','基础轮廓强度',0,100,'%'],['highlight','亮边强度',0,100,'%'],['shadedEdge','暗边强度',0,100,'%'],['angle','光线方向',0,360,'°'],['shadowOpacity','阴影强度',0,50,'%'],['shadowSize','阴影范围',0,40,'px'],['shadowOffset','阴影下移',0,20,'px']];
  colorDefs.push(['plateColor','底板底色']);
  numericDefs.push(['plateOpacity','底板不透明度',0,100,'%'],['plateBlur','底板模糊',0,60,'px'],['plateSaturation','底板饱和度',0,200,'%'],['plateBrightness','底板亮度',50,150,'%'],['plateHighlight','边缘高光',0,100,'%']);
  function read(){try{const saved=JSON.parse(localStorage.getItem(settingsKey)||'null');for(const name of ['light','dark','custom']){const profile={...defaults[name]},value=saved?.[name];for(const [key] of colorDefs)if(/^#[0-9a-f]{6}$/i.test(value?.[key]))profile[key]=value[key];for(const [key,,min,max] of numericDefs)if(Number.isFinite(value?.[key]))profile[key]=Math.max(min,Math.min(max,value[key]));if(typeof value?.cardColorCustom==='boolean')profile.cardColorCustom=value.cardColorCustom;if(typeof value?.plateEnabled==='boolean')profile.plateEnabled=value.plateEnabled;if(typeof value?.glowEnabled==='boolean')profile.glowEnabled=value.glowEnabled;if(['light','dark'].includes(value?.baseTheme))profile.baseTheme=value.baseTheme;if(['cover','contain','repeat'].includes(value?.imageFit))profile.imageFit=value.imageFit;settings[name]=profile;}const savedMode=localStorage.getItem(modeKey);mode=['light','dark','custom'].includes(savedMode)?savedMode:'light';}catch{}}
  const rgba=(hex,alpha)=>`rgba(${parseInt(hex.slice(1,3),16)},${parseInt(hex.slice(3,5),16)},${parseInt(hex.slice(5,7),16)},${alpha})`;
  function glowBackground(p,isDark){
    const width=innerWidth,height=innerHeight;
    const definitions=['left','right'].map(side=>{
      const right=side==='right',x=width*(right?(isDark?.70:.96):(isDark?.12:.08)),y=height*(right?(isDark?0:.20):(isDark?.52:.44));
      return `<radialGradient id="${side}" gradientUnits="userSpaceOnUse" cx="0" cy="0" r="1" gradientTransform="translate(${x} ${y}) rotate(${p[side+'Angle']}) scale(${p[side+'Width']/2} ${p[side+'Height']/2})"><stop offset="0" stop-color="${p[side+'Color']}" stop-opacity="${p[side+'Opacity']/100}"/><stop offset="${isDark?.80:.76}" stop-color="${p[side+'Color']}" stop-opacity="0"/></radialGradient>`;
    }).join('');
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs>${definitions}</defs><rect width="100%" height="100%" fill="url(#left)"/><rect width="100%" height="100%" fill="url(#right)"/></svg>`;
    return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
  }
  function apply(){const p=settings[mode],isDark=(mode==='dark'||mode==='custom'&&p.baseTheme==='dark');window.WorkbenchTheme.apply(isDark?'dark':'light');const style=document.documentElement.style;
    const values={'--paper':p.baseColor,'--collection-radius':p.listRadius+'px','--gallery-radius':p.galleryRadius+'px','--tag-radius':p.tagRadius+'px','--collection-glass-fill':rgba(p.fillColor,p.fill/100),'--collection-glass-outline':rgba(isDark?'#b8c3d6':'#596578',p.outline/100),'--collection-glass-highlight':rgba('#ffffff',p.highlight/100*(isDark?.4:1)),'--collection-glass-mid-edge':rgba(isDark?'#b8c3d6':'#596578',p.outline/200),'--collection-glass-shaded-edge':rgba(isDark?'#bfcde5':'#454e5d',p.shadedEdge/100),'--collection-glass-angle':p.angle+'deg','--collection-glass-blur':p.blur+'px','--collection-glass-saturation':p.saturation+'%','--collection-glass-shadow':`0 ${p.shadowOffset}px ${p.shadowSize}px ${rgba('#000000',p.shadowOpacity/100*(isDark?2:1))}`};for(const [key,value] of Object.entries(values))style.setProperty(key,value);
    document.documentElement.dataset.plateGlass=String(p.plateEnabled);
    style.setProperty('--plate-fill',rgba(p.plateColor,p.plateOpacity/100));
    style.setProperty('--plate-filter',p.plateEnabled?'blur('+p.plateBlur+'px) saturate('+p.plateSaturation+'%) brightness('+p.plateBrightness+'%)':'none');
    style.setProperty('--plate-edge',rgba(isDark?'#ffffff':'#8b9bb4',p.plateHighlight/100));
    style.setProperty('--plate-highlight',rgba('#ffffff',p.plateHighlight/100));
    const layers=[];if(mode==='custom'&&imageUrl){layers.push(`linear-gradient(${rgba(p.baseColor,1-p.imageOpacity/100)},${rgba(p.baseColor,1-p.imageOpacity/100)})`);layers.push(`url("${imageUrl}")`);}if(p.glowEnabled)layers.push(glowBackground(p,isDark));
    document.body.style.backgroundColor=p.baseColor;document.body.style.backgroundImage=layers.join(',')||'none';document.body.style.backgroundAttachment='fixed';document.body.style.backgroundPosition='center';document.body.style.backgroundSize=mode==='custom'&&imageUrl?`auto,${p.imageFit==='repeat'?'auto':p.imageFit},auto,auto`:'auto';document.body.style.backgroundRepeat=p.imageFit==='repeat'?'repeat':'no-repeat';
    style.setProperty('--app-background-image',document.body.style.backgroundImage);
    style.setProperty('--app-background-size',document.body.style.backgroundSize);
    style.setProperty('--app-background-repeat',document.body.style.backgroundRepeat);
    document.querySelectorAll('#viewerDialog,#editorDialog,#viewerDialog .dialog-actions,#editorDialog .dialog-actions').forEach(element=>{element.style.background=p.cardColorCustom?p.cardColor:'';});
    if(dialog)refresh();
  }
  function save(){try{localStorage.setItem(settingsKey,JSON.stringify(settings));localStorage.setItem(modeKey,mode);channel?.postMessage({imageChanged:false});showError('');}catch{showError('外观设置未能保存，请检查本地存储空间。');}}
  function showError(message){if(dialog)dialog.querySelector('[data-error]').textContent=message;}
  async function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open('knowledge-workbench-appearance',1);request.onupgradeneeded=()=>request.result.createObjectStore('backgrounds');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function imageStorage(action,value){const db=await database();try{return await new Promise((resolve,reject)=>{const transaction=db.transaction('backgrounds',action==='get'?'readonly':'readwrite'),store=transaction.objectStore('backgrounds');const request=action==='get'?store.get('custom'):action==='put'?store.put(value,'custom'):store.delete('custom');let result;request.onsuccess=()=>result=request.result;transaction.oncomplete=()=>resolve(result);transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error);});}finally{db.close();}}
  function replaceImage(blob,name=''){if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=blob?URL.createObjectURL(blob):null;imageName=name;}
  function refresh(){const p=settings[mode];dialog.querySelectorAll('[data-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.mode===mode)));dialog.querySelector('[data-custom]').hidden=mode!=='custom';dialog.querySelectorAll('[data-setting]').forEach(input=>{input.type==='checkbox'?input.checked=p[input.dataset.setting]:input.value=p[input.dataset.setting];const output=input.closest('label').querySelector('output');if(output)output.textContent=p[input.dataset.setting]+(input.dataset.unit||'');});dialog.querySelector('[data-image-name]').textContent=imageName||'未选择背景图片';dialog.querySelector('[data-remove]').disabled=!imageUrl||uploading;dialog.querySelector('[data-upload]').disabled=uploading;}
  function build(){dialog=document.createElement('section');dialog.id='appearanceDialog';dialog.setAttribute('aria-labelledby','appearanceHeading');dialog.innerHTML='<div class="appearance-head"><h2 id="appearanceHeading">外观设置</h2><button type="button" data-close aria-label="关闭外观设置">关闭</button></div><div class="appearance-modes" role="group" aria-label="外观模式"><button type="button" data-mode="light">浅色</button><button type="button" data-mode="dark">深色</button><button type="button" data-mode="custom">自定义</button></div><div data-custom hidden><label>界面配色<select data-setting="baseTheme"><option value="light">浅色</option><option value="dark">深色</option></select></label><div class="appearance-upload"><button type="button" data-upload>上传背景图片</button><button type="button" data-remove>移除图片</button><span class="appearance-note" data-image-name></span></div><input type="file" accept="image/*" data-file hidden><div class="appearance-fields"><label>图片显示方式<select data-setting="imageFit"><option value="cover">铺满</option><option value="contain">完整显示</option><option value="repeat">平铺</option></select></label></div></div><p class="appearance-note">修改即时预览并自动保存；浅色、深色、自定义分别保留参数。</p><div data-fields></div><p class="appearance-error" role="alert" data-error></p>';
    const groups=[['背景',['baseColor','glowEnabled','rightColor','rightOpacity','rightAngle','rightWidth','rightHeight','leftColor','leftOpacity','leftAngle','leftWidth','leftHeight','imageOpacity']],['底板玻璃效果',['plateEnabled','plateColor','plateOpacity','plateBlur','plateSaturation','plateBrightness','plateHighlight']],['卡片窗口',['cardColor']],['卡片与标签圆角',['listRadius','galleryRadius','tagRadius']],['卡片玻璃效果',['fillColor','fill','blur','saturation','outline','highlight','shadedEdge','angle','shadowOpacity','shadowSize','shadowOffset']]];
    for(const [title,keys] of groups){const fieldset=document.createElement('fieldset'),legend=document.createElement('legend'),fields=document.createElement('div');legend.textContent=title;fields.className='appearance-fields';fieldset.append(legend,fields);for(const key of keys){const label=document.createElement('label'),heading=document.createElement('span'),input=document.createElement('input'),definition=numericDefs.find(d=>d[0]===key);input.dataset.setting=key;heading.textContent=definition?.[1]||colorDefs.find(d=>d[0]===key)?.[1]||(key==='plateEnabled'?'启用底板玻璃':'柔和渐变');if(definition){input.type='range';input.min=definition[2];input.max=definition[3];input.step='.5';input.dataset.unit=definition[4];heading.append(document.createElement('output'));}else input.type=['glowEnabled','plateEnabled'].includes(key)?'checkbox':'color';label.append(heading,input);if(key==='imageOpacity')label.dataset.imageControl='';fields.append(label);}dialog.querySelector('[data-fields]').append(fieldset);}
    document.body.append(dialog);dialog.querySelector('[data-close]').onclick=()=>window.close();dialog.addEventListener('click',event=>{const button=event.target.closest('[data-mode]');if(button){mode=button.dataset.mode;apply();save();}});
    dialog.addEventListener('input',event=>{const input=event.target;if(!input.dataset.setting)return;if(input.dataset.setting==='cardColor')settings[mode].cardColorCustom=true;settings[mode][input.dataset.setting]=input.type==='range'?Number(input.value):input.type==='checkbox'?input.checked:input.value;apply();save();});
    dialog.querySelector('[data-upload]').onclick=()=>dialog.querySelector('[data-file]').click();dialog.querySelector('[data-file]').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;uploading=true;refresh();try{const probe=await createImageBitmap(file);probe.close();await imageStorage('put',{blob:file,name:file.name});replaceImage(file,file.name);mode='custom';apply();save();channel?.postMessage({imageChanged:true});}catch{showError('图片无法读取或保存，请选择有效的图片文件。');}finally{uploading=false;refresh();}};
    dialog.querySelector('[data-remove]').onclick=async()=>{uploading=true;refresh();try{await imageStorage('delete');replaceImage(null);apply();channel?.postMessage({imageChanged:true});}catch{showError('背景图片未能移除，请重试。');}finally{uploading=false;refresh();}};
    const originalRefresh=refresh;refresh=function(){originalRefresh();dialog.querySelector('[data-image-control]').hidden=mode!=='custom';};refresh();
  }
  read();apply();if(isSettingsWindow){build();}else {document.getElementById('themeToggle').addEventListener('click',()=>{
    if(settingsWindow&&!settingsWindow.closed){settingsWindow.focus();return;}
    settingsWindow=window.open(new URL('appearance.html',location.href).href,'workbench-appearance','popup,width=640,height=800,resizable=yes,scrollbars=yes');
  });
    document.getElementById('themeQuickToggle')?.addEventListener('click',()=>{mode=document.documentElement.dataset.theme==='dark'?'light':'dark';apply();save();});
  }
  function reloadImage(){return imageStorage('get').then(saved=>{replaceImage(saved?.blob||null,saved?.name||'');apply();}).catch(()=>{if(mode==='custom')showError('保存的背景图片暂时无法读取。');});}
  reloadImage();
  if(channel)channel.onmessage=event=>{read();apply();if(event.data?.imageChanged)reloadImage();};
  window.addEventListener('storage',event=>{if([settingsKey,modeKey].includes(event.key)){read();apply();}});
  let resizeFrame;window.addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(apply);});
})();
