import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, rm, stat, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const sandbox = await mkdtemp(path.join(tmpdir(), 'personalvault-canvas-'));
process.env.PERSONAL_VAULT_PATH = path.join(sandbox, 'vault');

try {
  const { saveCanvasDocument, loadCanvasDocument, getCanvasMediaDataUrl, getCanvasMediaUrl, getAsset, syncCards } = await import('../server.mjs');
  const cardId = 'knowledge-canvas-test';
  const snapshot = { update:'AQID', assets:{ image:'data:image/png;base64,AQID' },cardInfo:{title:'卡片A',type:'knowledge'},assetMetadata:{image:{name:'001.png'}} };
  await saveCanvasDocument(cardId, snapshot);
  const normalized = await loadCanvasDocument(cardId);
  assert.equal(normalized.update, snapshot.update);
  assert.deepEqual(normalized.assets, {});
  assert.equal(normalized.attachments.length, 1);
  assert.equal(normalized.linkedAssets.image, normalized.attachments[0].id);
  assert.deepEqual(await readFile(path.join(process.env.PERSONAL_VAULT_PATH,normalized.attachments[0].relativePath)),Buffer.from('AQID','base64'));
  await saveCanvasDocument(cardId, snapshot);
  const persisted=JSON.parse(await readFile(path.join(sandbox, 'vault', '系统', '自由画布', `${cardId}.json`), 'utf8'));
  assert.deepEqual(persisted.assets, {});
  assert.deepEqual(persisted.linkedAssets, normalized.linkedAssets, 'repeated saves reuse the same file');
  await assert.rejects(saveCanvasDocument('../escape', snapshot), /ID 无效/);
  await assert.rejects(saveCanvasDocument(cardId, { update:'AQID', assets:{ image:'https://example.com/image.png' } }), /资源格式无效/);
  assert.deepEqual(await loadCanvasDocument(cardId), normalized, 'invalid input must preserve the saved document');
  const linked = {...snapshot, assets:{}, linkedAssets:{'blob-1':'asset-1'}, primaryAssetId:'asset-1'};
  await assert.rejects(saveCanvasDocument(cardId, linked),/没有找到对应的文件记录/,'unknown references must not be reported as successfully saved');
  assert.deepEqual(await loadCanvasDocument(cardId),normalized,'failed reference validation preserves the saved canvas');
  await assert.rejects(saveCanvasDocument(cardId, {...linked, linkedAssets:{'blob-1':'../escape'}}), /关联资源无效/);
  await writeFile(path.join(sandbox,'vault','系统','自由画布','legacy.json'),JSON.stringify(snapshot));
  const migrated=await loadCanvasDocument('legacy');
  assert.equal(migrated.update,snapshot.update,'migration must preserve canvas layout data');
  assert.notEqual(migrated.linkedAssets.image,normalized.linkedAssets.image,'different cards own independent resources');
  assert.notEqual(migrated.attachments[0].relativePath,normalized.attachments[0].relativePath);
  assert.deepEqual(JSON.parse(await readFile(path.join(sandbox,'vault','系统','迁移备份','画布附件','legacy.json'),'utf8')),snapshot);
  assert.deepEqual(await loadCanvasDocument('legacy'),migrated,'migration must be idempotent');
  await saveCanvasDocument('cover-new',{...snapshot,coverSourceId:'image'});
  const chosen=await loadCanvasDocument('cover-new');
  assert.equal(chosen.coverAssetId,chosen.linkedAssets.image,'new inline media can be selected before its first save');
  await saveCanvasDocument('cover-new',{...chosen,coverAssetId:null});
  assert.equal((await loadCanvasDocument('cover-new')).coverAssetId,null,'automatic cover can be restored');
  await saveCanvasDocument('cover-new',{...chosen,linkedAssets:{},primaryAssetId:null,coverAssetId:chosen.coverAssetId});
  assert.equal((await loadCanvasDocument('cover-new')).coverAssetId,null,'removed media must not remain a cover');
  const files=[['报告.pdf','application/pdf','文档'],['音乐.mp3','audio/mpeg','音频'],['归档.zip','application/zip','其他'],['工具.exe','application/octet-stream','其他'],['空文件.txt','text/plain','文档']];
  const general={update:'AQID',assets:{},assetMetadata:{}};
  for(const [index,[name,mime]] of files.entries()){
    general.assets[`file-${index}`]=`data:${mime};base64,${index===4?'':Buffer.from(`binary fixture ${index}`).toString('base64')}`;
    general.assetMetadata[`file-${index}`]={name};
  }
  await saveCanvasDocument('general-files',general);
  const generalSaved=await loadCanvasDocument('general-files');
  assert.equal(generalSaved.attachments.length,files.length);
  for(const [index,[name,,category]] of files.entries()){
    const asset=generalSaved.attachments[index];
    assert.equal(asset.name,name);assert.equal(asset.category,category);
    const bytes=await readFile(path.join(process.env.PERSONAL_VAULT_PATH,asset.relativePath));
    assert.deepEqual(bytes,index===4?Buffer.alloc(0):Buffer.from(`binary fixture ${index}`));
    assert((await getCanvasMediaUrl(asset.id)).startsWith('file:'));
    assert.equal((await getCanvasMediaDataUrl(asset.id)).split(',')[1],bytes.toString('base64'));
  }
  await saveCanvasDocument('general-files',generalSaved);
  assert.deepEqual(await loadCanvasDocument('general-files'),generalSaved,'generic attachments survive saving and reopening');
  const retained={...generalSaved,linkedAssets:{'file-0':generalSaved.linkedAssets['file-0']}};
  await saveCanvasDocument('general-files',retained);
  assert.equal((await loadCanvasDocument('general-files')).attachments.length,1,'removing file blocks removes their attachment references');
  const modelBytes=Buffer.alloc(45*1024*1024,7);modelBytes.write('glTF');
  const modelSnapshot={update:'AQID',assets:{model:`data:application/octet-stream;base64,${modelBytes.toString('base64')}`},assetMetadata:{model:{name:'large-model.glb'}}};
  await saveCanvasDocument('model-files',modelSnapshot);
  const modelSaved=await loadCanvasDocument('model-files'),modelAsset=modelSaved.attachments[0],modelPath=path.join(process.env.PERSONAL_VAULT_PATH,modelAsset.relativePath);
  assert.equal(modelAsset.category,'模型');assert.equal(modelAsset.relativePath,'文件/资料/未命名卡片--model-files/large-model.glb');assert.deepEqual(await readFile(modelPath),modelBytes,'large models are copied byte for byte');
  await rm(modelPath);await assert.rejects(saveCanvasDocument('model-files',modelSaved),/附件文件缺失/,'a manifest record alone is not a saved file');
  assert.equal((await loadCanvasDocument('model-files')).linkedAssets.model,modelAsset.id,'failed save does not discard missing attachment references');
  await saveCanvasDocument('model-files',{...modelSnapshot,linkedAssets:modelSaved.linkedAssets});
  assert.equal((await loadCanvasDocument('model-files')).linkedAssets.model,modelAsset.id,'reinserting a missing model repairs the original asset record');assert.deepEqual(await readFile(modelPath),modelBytes);
  assert.equal(normalized.attachments[0].relativePath,`文件/知识/卡片A--${cardId}/001.png`);
  const originalFile=path.join(process.env.PERSONAL_VAULT_PATH,normalized.attachments[0].relativePath);
  const before=await stat(originalFile);
  await saveCanvasDocument(cardId,{...normalized,cardInfo:snapshot.cardInfo});
  assert.equal((await stat(originalFile)).mtimeMs,before.mtimeMs,'ordinary save does not copy an unchanged file');
  const twin=await saveCanvasDocument('card-B',{...snapshot,cardInfo:{title:'卡片B',type:'source'}});
  assert.notEqual(twin.snapshot.linkedAssets.image,normalized.linkedAssets.image);
  assert.equal(twin.attachments[0].relativePath,'文件/资料/卡片B--card-B/001.png');
  await rm(originalFile);
  assert.deepEqual(await readFile(path.join(process.env.PERSONAL_VAULT_PATH,twin.attachments[0].relativePath)),Buffer.from([1,2,3]),'deleting A does not affect B');
  await saveCanvasDocument(cardId,{...snapshot,linkedAssets:normalized.linkedAssets});
  const collision=await saveCanvasDocument(cardId,{...normalized,assets:{second:'data:image/png;base64,BAUG'},assetMetadata:{second:{name:'001.png'}},cardInfo:snapshot.cardInfo});
  assert.equal(collision.attachments[1].name,'001 (2).png');
  assert.deepEqual(await readFile(originalFile),Buffer.from([1,2,3]));
  const renamed=await saveCanvasDocument(cardId,{...collision.snapshot,cardInfo:{title:'新名称',type:'knowledge'}});
  assert(renamed.attachments.every(asset=>asset.relativePath.startsWith(`文件/知识/新名称--${cardId}/`)));
  assert.equal((await getAsset(normalized.linkedAssets.image)).relativePath,renamed.attachments[0].relativePath,'direct lookup follows folder rename');
  await syncCards({cards:[{id:cardId,title:'新名称',type:'capture'}]});
  assert.equal((await getAsset(normalized.linkedAssets.image)).relativePath,renamed.attachments[0].relativePath,'returning to inbox retains attachment directory');
  const legacyPath=path.join(process.env.PERSONAL_VAULT_PATH,'文件','图片','old.jpg');
  await mkdir(path.dirname(legacyPath),{recursive:true});await writeFile(legacyPath,Buffer.from([1,2,3]));
  const legacyRecord={id:'old-shared',displayName:'old.jpg',originalName:'old.jpg',relativePath:'文件/图片/old.jpg',size:3,category:'图片',extension:'.jpg'};
  const globalPath=path.join(process.env.PERSONAL_VAULT_PATH,'系统','assets-manifest.json');
  await writeFile(globalPath,JSON.stringify({assets:{'old-shared':legacyRecord}}));
  const old={update:'AQID',assets:{},linkedAssets:{image:'old-shared'},primaryAssetId:'old-shared',coverAssetId:'old-shared'};
  await writeFile(path.join(process.env.PERSONAL_VAULT_PATH,'系统','自由画布','old-A.json'),JSON.stringify(old));
  assert.equal((await loadCanvasDocument('old-A')).linkedAssets.image,'old-shared','reading legacy cards is non-destructive');
  const a=await saveCanvasDocument('old-A',{...old,cardInfo:{title:'旧卡A',type:'source'}});
  const b=await saveCanvasDocument('old-B',{...old,cardInfo:{title:'旧卡B',type:'project'}});
  assert.notEqual(a.snapshot.primaryAssetId,b.snapshot.primaryAssetId);
  assert.equal(a.snapshot.coverAssetId,a.snapshot.primaryAssetId);
  assert.equal(a.attachments[0].relativePath,'文件/资料/旧卡A--old-A/old.jpg');
  assert.equal(b.attachments[0].relativePath,'文件/项目/旧卡B--old-B/old.jpg');
  assert.deepEqual(await readFile(legacyPath),Buffer.from([1,2,3]),'legacy original remains available for other cards');
  assert.deepEqual(JSON.parse(await readFile(globalPath,'utf8')).assets,{'old-shared':legacyRecord},'new writes leave the global legacy inventory untouched');
  const stale=await saveCanvasDocument('old-A',old);
  assert.equal(stale.snapshot.primaryAssetId,a.snapshot.primaryAssetId,'repeated legacy references reuse this card’s copy');
  // A corrupt global inventory must not block any new-format card operation.
  await writeFile(globalPath,'not JSON');
  await saveCanvasDocument('card-B',twin.snapshot);
  assert.equal((await getAsset(twin.snapshot.linkedAssets.image)).size,3);
  assert.equal((await loadCanvasDocument('old-A')).attachments.length,1);
  console.log('canvas-document tests passed, including generic attachments, reopening and deletion');
} finally {
  assert.ok(path.resolve(sandbox).startsWith(path.resolve(tmpdir()) + path.sep));
  await rm(sandbox, { recursive:true, force:true });
}
